### ISSUE TITLE
The program loses layouts "ru"

### ISSUE THREAD

**Issue by pol1001** [zen-tools/gxkb#15] opened 2018-09-14 18:46 UTC
Hi, dear Zen. Big thanks for you program gxkb!
I like very much to use it.

But there is one thing: The program loses layouts "ru" for reasons unknown to me.
Disappears approximately 1 time per hour.
I do not do anything unusual. I communicate in skype. I'm watching YouTube. I'm working with virtual machines in virtualbox.
And suddenly I lose the opportunity to enter the text in Russian.
The layouts of "us" remains one, and "ru" disappears.
I look at the config right away - there are both layouts. 
But if you shut down the program, then only "us" remains in the config file.
If you configure the config and run the program, then everything is fine.
I tried to do "never_modify_config = true", then restarting the program did not help.
I tried to do "layouts = ru, us", but still "ru" disappears.
Please, tell me how to use your program in comfort? Or is it not a bug, but a feature ?!

I am used Ubuntu 16.04.5 LTS.
Kernel is 4.15.0-34-generic.
DE - Unity.

**Comment by zen-tools** [comment] 2018-09-16 18:16
Hi!

Yes, that is a bug. And it's related to issue #1. Unfortunately, I can't reproduce it on Debian 7/8/9 with Openbox. So, it should be environment specific issue. I will try to reproduce it with Ubuntu 16.04.5 LTS and will back with results.

**Comment by pol1001** [comment] 2018-09-16 19:10
Hi!
In addition to the programs I wrote above, I constantly start the background:
Drweb for Linux, GKrellM, Telegram, Psensor, Classic Menu Indicator.

Could you add the possibility of an audible alarm for an event when only one layout remains in the gxkb?At least temporarily! To make it easier to track what is happening with the gxkb.

Good luck.

**Comment by zen-tools** [comment] 2018-10-27 12:48
Hi!
I close this issue as duplicate. So, let's continue conversation in issue #1.

**Closed as completed by zen-tools** 2018-10-27 12:48 UTC
Labels: duplicate
