### ISSUE TITLE
Gxkb indicator not switching layout in some cases

### ISSUE THREAD

**Issue by Hryniuk1** [zen-tools/gxkb#30] opened 2020-11-05 10:54 UTC
Gxkb Version: 0.8.2 and 0.9.0 current master branch, both with appindicator support
System: Arch Linux, Debian Sid
DE: MATE Desktop.
Steps to reproduce (Use MATE Desktop)
1. Open gxkb via terminal, and minimize window
2. Open file manager and browser. Change layout by hotkey in browser window, then change it in filemanager window
3. Close file manager and browser
4. Try to change layout by hotkey. Indicator doesn't changing anything
If click to desktop once, gxkb is start to working again
Maximize terminal window and see this
**_[1604572590,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 2
![1604572590,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 2
![1604572590,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1604572590,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 0
![1604572591,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 2
![1604572591,000,xklavier_evt_xkb.c:xkl_xkb_process_x_event/] 	ATTENTION! Currently cached group 1 is not equal to the current group from the event: 2_**

**Comment by zen-tools** [comment] 2020-11-05 19:29
Hi! It looks more like WM issue. I guess, WM didn't change focus to the desktop after closing last active window. Also, I can't reproduce this issue with openbox.

**Closed as completed** 2024-02-06 21:13 UTC
